function switchLanguage(lang) {
    const elements = document.querySelectorAll('[data-lang]');
    elements.forEach(element => {
        if (translations[lang][element.dataset.lang]) {
            element.innerText = translations[lang][element.dataset.lang];
        }
    });
}


const translations = {
    'en': {
        portfolio_title: 'My Projects',
        portfolio_project1_title: 'Workshop Electrical Installation',
        portfolio_project1_desc: 'Sizing and schematics with Caneco BT (protections, cables, voltage drops).',
        portfolio_project2_title: 'Modeling & Electrical Simulation',
        portfolio_project2_desc: 'DC, induction and synchronous machines and solar systems in MATLAB/Simulink/Simscape.',
        portfolio_project3_title: 'Siemens PLC & HMI',
        portfolio_project3_desc: 'PLC programming for a marking system with HMI in TIA Portal.',
        portfolio_project4_title: 'Educational Sensor Prototype',
        portfolio_project4_desc: 'ESP32-based teaching prototype for acquisition and display.',
        portfolio_project5_title: 'Smart Home – IoT & Linux',
        portfolio_project5_desc: 'Started as BTS capstone then extended at ENSAM: Raspberry Pi, ESP32, Home Assistant, MQTT.',
        portfolio_project6_title: 'FlowShop Planner',
        portfolio_project6_desc: 'Python (Tkinter) scheduling app with solvers and Gantt chart.',
        portfolio_project7_title: 'Graph Theory Solver',
        portfolio_project7_desc: 'Python GUI solving classic graph problems (shortest path, max flow, etc.).',
        portfolio_project8_title: 'MRP2 Information System',
        portfolio_project8_desc: 'Production management information system in Microsoft Access.',
        portfolio_project9_title: 'Factory Optimization (Washing Machines)',
        portfolio_project9_desc: 'AnyLogic multi-agent simulation: flow, inventory, lots and overall profit.',
        portfolio_project10_title: 'Optimized Catapult',
        portfolio_project10_desc: 'Excel + VBA optimization (kriging, genetic algorithm, analysis).',
        portfolio_project11_title: 'Continuous Improvement – Production Line',
        portfolio_project11_desc: 'Lean tools – VSM, 5S, SMED – with QCD tracking.',
        portfolio_project12_title: 'Welded Parts Conformity',
        portfolio_project12_desc: 'Diagnosis and improvement of conformity in production.',
        portfolio_project13_title: 'Incremental Forming – Trajectory',
        portfolio_project13_desc: 'Trajectory for large-size part (CATIA V5 + RobotStudio).',
        portfolio_project14_title: 'V4 90° – Engine Modeling',
        portfolio_project14_desc: 'Study, modeling, simulation and balancing in 3DEXPERIENCE.',
        portfolio_project15_title: 'Bolted Assemblies',
        portfolio_project15_desc: 'Study and simulation in CATIA V5 (loads and constraints).',
        portfolio_project16_title: 'Milling CAM Simulation',
        portfolio_project16_desc: 'CAM simulation and machining of a prismatic part (CATIA V5).',
        portfolio_project17_title: 'XR Showroom – Meta Quest 3',
        portfolio_project17_desc: 'Interactive XR app in Unity + Blender for Quest 3.',
        portfolio_project18_title: 'UNIROSS Environmental Study',
        portfolio_project18_desc: 'Life-cycle assessment in SimaPro (use and end-of-life scenarios).',
        portfolio_project19_title: 'Hydraulic Conveyor Simulation',
        portfolio_project19_desc: 'Sorting system simulation with hydraulic cylinders (Automation Studio).',
        'nav_home': 'Home',
        'nav_about': 'About',
        'nav_services': 'Services',
        'nav_studies': 'Studies',
        'nav_portfolio': 'My Projects',
        'header_title': 'Hi!',
        'header_subtitle': 'I am Salah Eddine Maimouni',
        'header_subtitle2': 'Engineering Student',
        'github_btn': 'Visit my GitHub',
        'linkedin_btn': 'Visit my LinkedIn',
        'about_me': 'About Me',
        'about_description': 'Who am I?',
        'about_text': 'I am an engineering student at Arts et Métiers Metz in my third year. I also completed two years of electromechanical engineering at ENSAM Casablanca after earning a Higher Technician Diploma (BTS) in Electrical Engineering, and I am currently looking for an apprenticeship or internship opportunity.',
        'about_cv_btn': 'Download CV',
        'services_title': 'Services',
        'service_electrical_title': 'Electrical',
        'service_electrical_desc': 'Design, simulation, maintenance, and construction of automatic electrical and electronic systems',
        'service_mechanical_title': 'Mechanical',
        'service_mechanical_desc': 'Design, simulation, maintenance, and construction of mechanical systems and 3D modeling',
        'service_embedded_title': 'Embedded Systems',
        'service_embedded_desc': 'Programming, construction, and maintenance of embedded systems using C, C++, Python, and assembly language',
        'service_dev_title': 'Development',
        'service_dev_desc': 'Graphical user interfaces, object-oriented programming, computer vision, front and back-end web development',
        'studies_title': 'Studies',
        'study1_name': 'Professional Baccalaureate',
        'study1_description': 'Professional Baccalaureate in Industrial Maintenance, obtained in 2020 at Jerada Zeraktouni High School and OFPPT',
        'study2_name': 'BTS in Electrotechnics',
        'study2_description': 'Higher Technician Diploma in Electrotechnics, obtained in 2022 at Mehdi Ben Berka Technical High School in Oujda',
        'study3_name': 'ENSAM CASABLANCA',
        'study3_description': 'Electromechanical Engineering Diploma started in 2022 at ENSAM Casablanca',
        'study4_name': 'ENSAM METZ',
        'study4_description': 'General Engineering Diploma started in 2024 at ENSAM Metz',
        'internship_title': 'Internships',
        'internship1_title': 'Digital Resources Maintenance 1 month /2021',
        'internship1_desc': 'Maintenance of PCs, printers, LCD screens at the National Laboratory of Digital Resources in Rabat',
        'internship2_title': 'Machine Tool Maintenance 1 month/2022',
        'internship2_desc': 'Maintenance of electrical installations of machine tools at Mehdi Ben Berka Technical High School in Oujda',
        'internship3_title': 'Water Pump Maintenance 2 months /2023',
        'internship3_desc': 'Maintenance of water distribution circuits and their electrical installations at ONEE-BO Jerada',
        'internship4_title': 'Calculation and monitoring of the performance of the 350 MW thermal power plant 2 months /2024',
        'internship4_desc': 'According to the ASME PTC 46 standard I calculated the performance of the thermal station at ONEE-BE Jerada',
        'portfolio_title': 'My Projects',
        'contact_title': 'Contact Me'
    },
    'fr': {
        portfolio_title: 'Mes Projets',
        portfolio_project1_title: 'Installation électrique d’atelier',
        portfolio_project1_desc: 'Dimensionnement et schémas sous Caneco BT (protections, sections, chutes de tension).',
        portfolio_project2_title: 'Modélisation & simulation électrotech',
        portfolio_project2_desc: 'Moteurs CC, MAS, MS et systèmes solaires sous MATLAB/Simulink/Simscape.',
        portfolio_project3_title: 'API Siemens & IHM',
        portfolio_project3_desc: 'Programmation d’un API Siemens pour marquage et interface HMI sous TIA Portal.',
        portfolio_project4_title: 'Maquette didactique de capteur',
        portfolio_project4_desc: 'Prototype pédagogique à base d’ESP32 pour acquisition et visualisation.',
        portfolio_project5_title: 'Smart Home – IoT & Linux',
        portfolio_project5_desc: 'Projet démarré en PFE de BTS puis complété en 2ᵉ année ENSAM : Raspberry Pi, ESP32, Home Assistant, MQTT.',
        portfolio_project6_title: 'FlowShop Planner',
        portfolio_project6_desc: 'Application Python (Tkinter) pour ordonnancement, solveurs et diagramme de Gantt.',
        portfolio_project7_title: 'Solveur de graphes',
        portfolio_project7_desc: 'Outil Python GUI pour problèmes de théorie des graphes (chemins, flots…).',
        portfolio_project8_title: 'Système d’information MRP2',
        portfolio_project8_desc: 'Gestion de production MRP2 sous Microsoft Access (tables, requêtes, formulaires).',
        portfolio_project9_title: 'Optimisation d’usine (machines à laver)',
        portfolio_project9_desc: 'Simulation AnyLogic : flux, stocks, lots, performances et profit global.',
        portfolio_project10_title: 'Catapulte Optimisée',
        portfolio_project10_desc: 'Optimisation via Excel + VBA (krigeage, algorithme génétique, analyse).',
        portfolio_project11_title: 'Amélioration continue – Ligne de production',
        portfolio_project11_desc: 'VSM, 5S, SMED et suivi QCD pour gains de performance.',
        portfolio_project12_title: 'Conformité mécano-soudées',
        portfolio_project12_desc: 'Diagnostic et amélioration de la conformité en production.',
        portfolio_project13_title: 'Formage incrémental – Trajectoire',
        portfolio_project13_desc: 'Trajectoire pour grande pièce (CATIA V5 + RobotStudio).',
        portfolio_project14_title: 'V4 90° – Modélisation moteur',
        portfolio_project14_desc: 'Étude, modélisation, simulation et équilibrage (3DEXPERIENCE).',
        portfolio_project15_title: 'Assemblages vissés',
        portfolio_project15_desc: 'Étude et simulation sous CATIA V5 (contraintes, efforts).',
        portfolio_project16_title: 'Usinage sur fraiseuse',
        portfolio_project16_desc: 'Simulation FAO et usinage d’une pièce prismatique (CATIA V5).',
        portfolio_project17_title: 'XR Showroom – Meta Quest 3',
        portfolio_project17_desc: 'Application XR interactive sous Unity + Blender (Quest 3).',
        portfolio_project18_title: 'Étude environnementale UNIROSS',
        portfolio_project18_desc: 'ACV des piles sous SimaPro (scénarios d’usage et fin de vie).',
        portfolio_project19_title: 'Tapis roulant hydraulique',
        portfolio_project19_desc: 'Simulation de tri par vérins hydrauliques (Automation Studio).',
        'nav_home': 'Accueil',
        'nav_about': 'À propos',
        'nav_services': 'Services',
        'nav_studies': 'Études',
        'nav_portfolio': 'Mes Projets',
        'header_title': 'Salut!',
        'header_subtitle': 'Je suis Salah Eddine Maimouni',
        'header_subtitle2': 'Étudiant ingénieur',
        'github_btn': 'Visitez mon GitHub',
        'linkedin_btn': 'Visitez mon LinkedIn',
        'about_me': 'À propos de moi',
        'about_description': 'Qui suis-je?',
        'about_text': "Je suis élève-ingénieur à l’Arts et Métiers de Metz en troisième année. J’ai également effectué deux années d’ingénierie en électromécanique à l’ENSAM Casablanca après l’obtention d’un BTS en électrotechnique, et je suis actuellement à la recherche d’une opportunité d’alternance ou de stage.",
        'about_cv_btn': 'Télécharger CV',
        'services_title': 'Services',
        'service_electrical_title': 'Électrique',
        'service_electrical_desc': 'Conception, simulation, maintenance et construction de systèmes électriques et électroniques automatiques',
        'service_mechanical_title': 'Mécanique',
        'service_mechanical_desc': 'Conception, simulation, maintenance et construction de systèmes mécaniques et modélisation 3D',
        'service_embedded_title': 'Systèmes Embarqués',
        'service_embedded_desc': 'Programmation, construction et maintenance de systèmes embarqués utilisant C, C++, Python et l\'assembleur',
        'service_dev_title': 'Développement',
        'service_dev_desc': 'Interfaces utilisateur graphiques, programmation orientée objet, vision par ordinateur, développement web front et back-end',
        'studies_title': 'Études',
        'study1_name': 'Baccalauréat Professionnel',
        'study1_description': 'Baccalauréat Professionnel en Maintenance Industrielle, obtenu en 2020 au Lycée Jerada Zeraktouni et à l\'OFPPT',
        'study2_name': 'BTS en Électrotechnique',
        'study2_description': 'Diplôme de Technicien Supérieur en Électrotechnique, obtenu en 2022 au Lycée Technique Mehdi Ben Berka à Oujda',
        'study3_name': 'ENSAM CASABLANCA',
        'study3_description': 'Diplôme d\'Ingénieur en Électromécanique entamé en 2022 à l\'ENSAM Casablanca',
        'study4_name': 'ENSAM METZ',
        'study4_description': 'Diplôme d\'Ingénieur généraliste PGE (Programme Grande École) entamé en 2024 à l\'ENSAM Metz',
        'internship_title': 'Stages',
        'internship1_title': 'Maintenance des Ressources Numériques 1 mois /2021',
        'internship1_desc': 'Maintenance des PC, imprimantes, écrans LCD au Laboratoire National des Ressources Numériques à Rabat',
        'internship2_title': 'Maintenance des Machines-Outils 1 mois /2022',
        'internship2_desc': 'Maintenance des installations électriques des machines-outils au Lycée Technique Mehdi Ben Berka à Oujda',
        'internship3_title': 'Maintenance des Pompes de Distribution d\'Eau 2 mois /2024',
        'internship3_desc': 'Maintenance des circuits de distribution d\'eau et de leurs installations électriques à l\'ONEE-BO Jerada',
        'internship4_title': 'Calcul et suivi des performances de la centrale thermique 350MW 2 mois /2024',
        'internship4_desc': 'Selon la norme ASME PTC 46 j\'ai calculé les performances de la station thermique à l\'ONEE-BE Jerada',
        'portfolio_title': 'Mes Projets',
        'contact_title': 'Contactez-Moi'
    }
};

// On page load, set the initial language to English
document.addEventListener('DOMContentLoaded', function () {
    switchLanguage('en');
});




